//this program finds number from array (generated by Rand ()//
#include<stdio.h>
#include <iostream>
#include<stdlib.h>
using namespace std;
main()
{
	int a[100];
	int z, i;
//initializing array//
for (i=0;i<100;i++)
	{
	a[i] = rand();
	}
cout<<"please enter a +ive number : ";
cin>>z;
int found = 0;
//loop to search number
for (i=0;i<100;i++)
{
	if (z == a[i])
	{
		found = 1;
		break;
	}
}		if (found ==1)
		cout<<"we found the integer at postion "<<i;
		else
		cout<<"number not found";
}


